version: "3"
services:
    web:
        build: ./
        image: webserver
        container_name: webserver
        hostname: webserver
        restart: unless-stopped
        ports:
            - "8080:8080"
        links:
            - db
        depends_on:
            - db
        networks:
          services-network:
              aliases:
                  - web
        
    db: 
        build: ./db
        image: postgresdb
        container_name: postgresdb
        hostname: postgresdb
        ports:
            - "5432:5432"
        expose:
            - "5432"    
        volumes:
            - ./db/students.sql:/docker-entrypoint-initdb.d/students.sql 
        networks:
          services-network:
              aliases:
                  - db
networks:
   services-network:
     driver: bridge
